services:
  node:
    container_name: tgtg-notifier-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./config.json:/usr/app/config.json
      - ./logs/:/usr/app/logs
